---
title: "ADHD"
author: "Matthew Zelenin"
date: "12/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(MASS)
library(dplyr)
library(tidyr)
library(alr4)
library(ggplot2)
library(gridExtra)
library(splines)
```

## Filtering Data

```{r message=FALSE, warning=FALSE, echo=FALSE, size="tiny"}
kki_demographics = read.csv('data/KKI_demographicInfo.csv')
kki_handedness = read.csv('data/KKI_handedness.csv')
kki_mABC = read.csv('data/KKI_movementAssessmentBatteryforChildren.csv')
kki_SRS = read.csv('data/KKI_SocialResponsivenessScaleQuestionnaire.csv')
kki_WISC = read.csv('data/KKI_WechslerIntelligenceScaleforChildren.csv')


full_dat = full_join(kki_demographics, kki_mABC)
full_dat = full_join(full_dat, kki_SRS)
full_dat = full_join(full_dat, kki_WISC)
full_dat = full_join(full_dat, kki_handedness)
```

```{r message=FALSE, warning=FALSE}
full_dat = full_dat %>% drop_na(c('SecondaryDiagnosis', 
                                  'CurrentlyNotTakingMeds', 
                                  'CurrentlyTakingAtomoxetine', 
                                  'CurrentlyTakingClonidine', 
                                  'mABC_TotalStandardScore', 
                                  'EdinburghHandedness_Integer'))
full_dat = subset(full_dat, visit == 1)
full_dat = subset(full_dat, !is.na(WISC_VERSION) & !is.na(SRS_VERSION))
full_dat = subset(full_dat, ADHD_Subtype %in% c('Combined', 
                                                'Hyperactive/Impulsive', 
                                                'Inattentive', 
                                                'No dx'))
```

```{r}
library(dplyr)

wisc4_lookup_tab = read.csv('data/wisc4GAI_lookup.csv')
wisc5_lookup_tab = read.csv('data/wisc5GAI_lookup.csv')

wisc = read.csv('data/KKI_WechslerIntelligenceScaleforChildren.csv')

wisc = as_tibble(wisc)

# Cannot make conversion if do not know version
wisc = wisc %>% 
  filter(!is.na(WISC_VERSION))

wisc4_vars = names(wisc)[5:10]
wisc5_vars = names(wisc)[11:15]

wisc$scaled_sum = rep(0, dim(wisc)[1])


for (i in 1:dim(wisc)[1]) {
  if (wisc[i,]$WISC_VERSION == 4) {
    wisc[i,]$scaled_sum = sum(wisc[i, wisc4_vars])
  } else {
    wisc[i,]$scaled_sum = sum(wisc[i, wisc5_vars])
  }
}

wisc = wisc %>%
  select(-c(wisc4_vars, wisc5_vars)) %>%
  filter(!is.na(scaled_sum))



sum_to_gai = function(version, sum) {
  if (version == 4) {
    return (wisc4_lookup_tab$WISC4.GAI[which(wisc4_lookup_tab$WISC4.ScaledSum == sum)])
  } else {
    return (wisc5_lookup_tab$WISC5.GAI[which(wisc5_lookup_tab$WISC5.ScaledSum == sum)])
  }
}


wisc = wisc %>%
  rowwise() %>%
  mutate(GAI = sum_to_gai(WISC_VERSION, scaled_sum))

write.csv(wisc, 'data/KKI_GAI_from_WISC')
```

```{r}
full_dat = left_join(full_dat, wisc)
full_dat = subset(full_dat, select = c(1:5, 10, 11, 15, 18, 22, 25, 26, 42))
full_dat$SRS_VERSION = as.factor(full_dat$SRS_VERSION)
full_dat = full_dat %>% drop_na(c('GAI'))
```



```{r}
full_dat_ADHD = subset(full_dat, PrimaryDiagnosis == 'ADHD')
full_dat_ADHD = subset(full_dat_ADHD, ADHD_Subtype %in% c('Combined', 'Inattentive'))
row.names(full_dat_ADHD) = 1:nrow(full_dat_ADHD)
```

```{r}
full_dat_ADHD_V1 = subset(full_dat_ADHD, SRS_VERSION == 1)
full_dat_ADHD_V2 = subset(full_dat_ADHD, SRS_VERSION == 2)
ggplot(full_dat_ADHD_V1, aes(x=SRS_TotalRawScore)) + geom_histogram()
ggplot(full_dat_ADHD_V2, aes(x=SRS_TotalRawScore)) + geom_histogram()
ggplot(full_dat_ADHD_V1, aes(x=mABC_TotalStandardScore)) + geom_histogram()
ggplot(full_dat_ADHD_V2, aes(x=mABC_TotalStandardScore)) + geom_histogram()
```

```{r}
ggplot(full_dat_ADHD, aes(x=SRS_TotalRawScore)) + geom_histogram()
ggplot(full_dat_ADHD, aes(x=mABC_TotalStandardScore)) + geom_histogram()
ggplot(full_dat_ADHD, aes(x=mABC_AGE)) + geom_histogram()
```

```{r}
ggplot(full_dat_ADHD, aes(full_dat_ADHD$mABC_TotalStandardScore, full_dat_ADHD$SRS_TotalRawScore)) + geom_point() + geom_jitter(alpha = 1)
```

```{r}
lm_mABC_total = lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + SRS_VERSION, full_dat_ADHD)
lm_mABC_components = lm(SRS_TotalRawScore ~ mABC_ManualDexterity.Component.StandardScore + mABC_AimingAndCatching.Component.StandardScore + mABC_Balance.Component.StandardScore + SRS_VERSION, full_dat_ADHD)
anova(lm_mABC_components, lm_mABC_total)
```

```{r}
lm_gender = lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + SRS_VERSION + Gender, full_dat_ADHD)
lm_age = lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + SRS_VERSION + mABC_AGE, full_dat_ADHD)
lm_sd = lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + SRS_VERSION + SecondaryDiagnosis, full_dat_ADHD)
lm_subtype = lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + SRS_VERSION + ADHD_Subtype, full_dat_ADHD)
lm_GAI = lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + SRS_VERSION + GAI, full_dat_ADHD)

summary(lm_mABC_total)
summary(lm_gender)
summary(lm_age)
summary(lm_sd)
summary(lm_subtype)
summary(lm_GAI)
```

```{r}
anova(lm_gender, lm_mABC_total)
anova(lm_age, lm_mABC_total)
anova(lm_sd, lm_mABC_total)
anova(lm_subtype, lm_mABC_total)
anova(lm_GAI, lm_mABC_total)
```

```{r}
lm_mABC_sd_sub = lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + SRS_VERSION + SecondaryDiagnosis + ADHD_Subtype, full_dat_ADHD)
summary(lm_mABC_sd_sub)
plot(fitted(lm_mABC_sd_sub), stdres(lm_mABC_sd_sub))
qqnorm(stdres(lm_mABC_sd_sub))
qqline(stdres(lm_mABC_sd_sub))
```

```{r}
plot(influence(lm_mABC_sd_sub)$hat, stdres(lm_mABC_sd_sub))
```

```{r}
order(stdres(lm_mABC_sd_sub), decreasing = TRUE)
stdres(lm_mABC_sd_sub)[c(140, 134, 169)]
full_dat_ADHD_filtered = full_dat_ADHD[-c(140, 134, 169),]
```

```{r}
lm_mABC_sd_sub_filtered = lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + SRS_VERSION + SecondaryDiagnosis + ADHD_Subtype, full_dat_ADHD_filtered)
summary(lm_mABC_sd_sub_filtered)
plot(fitted(lm_mABC_sd_sub_filtered), stdres(lm_mABC_sd_sub_filtered))
qqnorm(stdres(lm_mABC_sd_sub_filtered))
qqline(stdres(lm_mABC_sd_sub_filtered))
```

```{r}
lm_mABC_sd_sub_interaction_filtered = lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + SRS_VERSION + SecondaryDiagnosis * ADHD_Subtype, full_dat_ADHD_filtered)
summary(lm_mABC_sd_sub_interaction_filtered)
plot(fitted(lm_mABC_sd_sub_interaction_filtered), stdres(lm_mABC_sd_sub_interaction_filtered))
qqnorm(stdres(lm_mABC_sd_sub_interaction_filtered))
qqline(stdres(lm_mABC_sd_sub_interaction_filtered))
```

```{r}
lm_mABCmd_sd_sub_interaction_filtered = lm(SRS_TotalRawScore ~ mABC_ManualDexterity.Component.StandardScore + SRS_VERSION + SecondaryDiagnosis * ADHD_Subtype, full_dat_ADHD_filtered)
summary(lm_mABCmd_sd_sub_interaction_filtered)
```

```{r}
lm_mABCaac_sd_sub_interaction_filtered = lm(SRS_TotalRawScore ~ mABC_AimingAndCatching.Component.StandardScore + SRS_VERSION + SecondaryDiagnosis * ADHD_Subtype, full_dat_ADHD_filtered)
summary(lm_mABCaac_sd_sub_interaction_filtered)
```

```{r}
lm_mABCbal_sd_sub_interaction_filtered = lm(SRS_TotalRawScore ~ mABC_Balance.Component.StandardScore + SRS_VERSION + SecondaryDiagnosis * ADHD_Subtype, full_dat_ADHD_filtered)
summary(lm_mABCbal_sd_sub_interaction_filtered)
plot(fitted(lm_mABCbal_sd_sub_interaction_filtered), stdres(lm_mABCbal_sd_sub_interaction_filtered))
qqnorm(stdres(lm_mABCbal_sd_sub_interaction_filtered))
qqline(stdres(lm_mABCbal_sd_sub_interaction_filtered))
```

```{r}
lm_mABCbalsquared_sd_sub_interaction_filtered = lm(SRS_TotalRawScore ~ I(mABC_Balance.Component.StandardScore^2) + SRS_VERSION + SecondaryDiagnosis * ADHD_Subtype, full_dat_ADHD_filtered)
summary(lm_mABCbalsquared_sd_sub_interaction_filtered)
plot(fitted(lm_mABCbalsquared_sd_sub_interaction_filtered), stdres(lm_mABCbalsquared_sd_sub_interaction_filtered))
qqnorm(stdres(lm_mABCbalsquared_sd_sub_interaction_filtered))
qqline(stdres(lm_mABCbalsquared_sd_sub_interaction_filtered))
```

```{r}
lm_mABCbalcubed_sd_sub_interaction_filtered = lm(SRS_TotalRawScore ~ I(mABC_Balance.Component.StandardScore^3) + SRS_VERSION + SecondaryDiagnosis * ADHD_Subtype, full_dat_ADHD_filtered)
summary(lm_mABCbalcubed_sd_sub_interaction_filtered)
plot(fitted(lm_mABCbalcubed_sd_sub_interaction_filtered), stdres(lm_mABCbalcubed_sd_sub_interaction_filtered))
qqnorm(stdres(lm_mABCbalcubed_sd_sub_interaction_filtered))
qqline(stdres(lm_mABCbalcubed_sd_sub_interaction_filtered))
```

```{r}
full_dat_ADHD_filtered$fitted_SRS_TotalRawScore <- 
predict(lm_mABCbal_sd_sub_interaction_filtered, newdata = full_dat_ADHD_filtered)

ggplot(full_dat_ADHD_filtered, aes(mABC_TotalStandardScore, SRS_TotalRawScore)) + geom_point() + geom_jitter() + geom_smooth() + geom_smooth(aes(mABC_TotalStandardScore, fitted_SRS_TotalRawScore), full_dat_ADHD_filtered, method = 'lm', col = 'red', lty = 2)
```
