---
title: "ADHD"
author: "Matthew Zelenin"
date: "12/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(tidyr)
library(alr4)
library(ggplot2)
library(gridExtra)
```

## Filtering Data

```{r message=FALSE, warning=FALSE, echo=FALSE, size="tiny"}
kki_demographics = read.csv('data/KKI_demographicInfo.csv')
kki_handedness = read.csv('data/KKI_handedness.csv')
kki_mABC = read.csv('data/KKI_movementAssessmentBatteryforChildren.csv')
kki_SRS = read.csv('data/KKI_SocialResponsivenessScaleQuestionnaire.csv')
kki_WISC = read.csv('data/KKI_WechslerIntelligenceScaleforChildren.csv')


full_dat = full_join(kki_demographics, kki_mABC)
full_dat = full_join(full_dat, kki_SRS)
full_dat = full_join(full_dat, kki_WISC)
full_dat = full_join(full_dat, kki_handedness)
```

```{r message=FALSE, warning=FALSE}
full_dat = full_dat %>% drop_na(c('SecondaryDiagnosis', 
                                  'CurrentlyNotTakingMeds', 
                                  'CurrentlyTakingAtomoxetine', 
                                  'CurrentlyTakingClonidine', 
                                  'mABC_TotalStandardScore', 
                                  'EdinburghHandedness_Integer'))
full_dat = subset(full_dat, visit == 1)
full_dat = subset(full_dat, !is.na(WISC_VERSION) & !is.na(SRS_VERSION))
full_dat = subset(full_dat, ADHD_Subtype %in% c('Combined', 
                                                'Hyperactive/Impulsive', 
                                                'Inattentive', 'No dx'))

WISC4_full_dat = subset(full_dat, WISC_VERSION == 4)
WISC5_full_dat = subset(full_dat, WISC_VERSION == 5)
```

```{r}
library(dplyr)

wisc4_lookup_tab = read.csv('data/wisc4GAI_lookup.csv')
wisc5_lookup_tab = read.csv('data/wisc5GAI_lookup.csv')

wisc = read.csv('data/KKI_WechslerIntelligenceScaleforChildren.csv')

wisc = as_tibble(wisc)

# Cannot make conversion if do not know version
wisc = wisc %>% 
  filter(!is.na(WISC_VERSION))

wisc4_vars = names(wisc)[5:10]
wisc5_vars = names(wisc)[11:15]

wisc$scaled_sum = rep(0, dim(wisc)[1])


for (i in 1:dim(wisc)[1]) {
  if (wisc[i,]$WISC_VERSION == 4) {
    wisc[i,]$scaled_sum = sum(wisc[i, wisc4_vars])
  } else {
    wisc[i,]$scaled_sum = sum(wisc[i, wisc5_vars])
  }
}

wisc = wisc %>%
  select(-c(wisc4_vars, wisc5_vars)) %>%
  filter(!is.na(scaled_sum))



sum_to_gai = function(version, sum) {
  if (version == 4) {
    return (wisc4_lookup_tab$WISC4.GAI[which(wisc4_lookup_tab$WISC4.ScaledSum == sum)])
  } else {
    return (wisc5_lookup_tab$WISC5.GAI[which(wisc5_lookup_tab$WISC5.ScaledSum == sum)])
  }
}


wisc = wisc %>%
  rowwise() %>%
  mutate(GAI = sum_to_gai(WISC_VERSION, scaled_sum))

write.csv(wisc, 'data/KKI_GAI_from_WISC')
```

```{r}
full_dat = left_join(full_dat, wisc)
full_dat = subset(full_dat, select = c(1:5, 10, 11, 15, 18, 22, 25, 26, 42))
```

