---
title: "Exploratory Data Analysis"
author:
- Gabriel Lahman
- Rowan Lavelle
- Jordan Majoros
- Matthew Zelenin
date: "11/11/2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(alr4)

kki_demographics = read.csv('data/KKI_demographicInfo.csv')
kki_handedness = read.csv('data/KKI_handedness.csv')
kki_mABC = read.csv('data/KKI_movementAssessmentBatteryforChildren.csv')
kki_SRS = read.csv('data/KKI_SocialResponsivenessScaleQuestionnaire.csv')
kki_WISC = read.csv('data/KKI_WechslerIntelligenceScaleforChildren.csv')


full_dat = full_join(kki_demographics, kki_mABC)
full_dat = full_join(full_dat, kki_SRS)
full_dat = full_join(full_dat, kki_WISC)
full_dat = full_join(full_dat, kki_handedness)
full_dat = full_dat %>% drop_na(c('SecondaryDiagnosis', 'CurrentlyNotTakingMeds', 'CurrentlyTakingAtomoxetine', 'CurrentlyTakingClonidine', 'mABC_TotalStandardScore', 'EdinburghHandedness_Integer'))
full_dat = subset(full_dat, !(is.na(SRS_VERSION) & is.na(WISC_VERSION)))
WISC4_full_dat = subset(full_dat, WISC_VERSION == 4)
WISC5_full_dat = subset(full_dat, WISC_VERSION == 5)
```


## Research Question

Is there a statistically significant difference in predictive power of the motor skills vs. social responsivness model when we include intelligence metrics as predictors?





```{r message=FALSE, warning=FALSE, fig.align='center'}
library(ggplot2)
ggplot(full_dat, aes(x=PrimaryDiagnosis, y=mABC_TotalStandardScore, color=PrimaryDiagnosis)) + 
  geom_boxplot()
```

```{r message=FALSE, warning=FALSE, fig.align='center'}
ggplot(full_dat, aes(x=mABC_AGE, y=mABC_TotalStandardScore)) + 
  geom_jitter() + 
  ggtitle('Age vs. mABC Total Standard Score')
```

```{r message=FALSE, warning=FALSE, fig.align='center'}
ggplot(full_dat, aes(x= WISC4_Vocabulary, y=mABC_TotalStandardScore)) + 
  geom_jitter() +
  facet_grid(. ~ PrimaryDiagnosis) + 
  ggtitle('WISC4_Vocabulary vs. mABC Total Standard Score')
```

```{r message=FALSE, warning=FALSE, fig.align='center'}
ggplot(full_dat, aes(x= WISC5_Vocabulary, y=mABC_TotalStandardScore)) + 
  geom_jitter() +
  facet_grid(. ~ PrimaryDiagnosis) + 
  ggtitle('WISC5_Vocabulary vs. mABC Total Standard Score')
```

```{r message=FALSE, warning=FALSE, fig.align='center'}
ggplot(full_dat, aes(x= WISC4_Information, y=mABC_TotalStandardScore)) + 
  geom_jitter() +
  facet_grid(. ~ PrimaryDiagnosis) + 
  ggtitle('WISC4_Information vs. mABC Total Standard Score')
```

```{r message=FALSE, warning=FALSE, fig.align='center'}
ggplot(full_dat, aes(x= WISC4_Similarities, y=mABC_TotalStandardScore)) + 
  geom_jitter() +
  facet_grid(. ~ PrimaryDiagnosis) + 
  ggtitle('WISC4_Similarities vs. mABC Total Standard Score')
```


```{r message=FALSE, warning=FALSE, fig.align='center'}
ggplot(full_dat, aes(x= WISC5_Similarities, y=mABC_TotalStandardScore)) + 
  geom_jitter() +
  facet_grid(. ~ PrimaryDiagnosis) + 
  ggtitle('WISC5_Similarities vs. mABC Total Standard Score')
```


```{r message=FALSE, warning=FALSE, fig.align='center'}
ggplot(full_dat, aes(x= WISC4_BlockDesign, y=mABC_TotalStandardScore)) + 
  geom_jitter() +
  facet_grid(. ~ PrimaryDiagnosis) + 
  ggtitle('WISC4_Design vs. mABC Total Standard Score')
```



```{r message=FALSE, warning=FALSE, fig.align='center'}
ggplot(full_dat, aes(x= WISC4_PictureConcepts, y=mABC_TotalStandardScore)) + 
  geom_jitter() +
  facet_grid(. ~ PrimaryDiagnosis) + 
  ggtitle('WISC4_PictureConcepts vs. mABC Total Standard Score')
```

```{r}
scatterplotMatrix(WISC4_full_dat[c('WISC4_Vocabulary', 'WISC4_Information', 'WISC4_Similarities', 'WISC4_BlockDesign', 'WISC4_PictureConcepts', 'WISC4_MatrixReasoning')], cex = 0.2)
```

```{r}
scatterplotMatrix(WISC5_full_dat[c('WISC5_Vocabulary', 'WISC5_Similarities', 'WISC5_BlockDesign', 'WISC5_MatrixReasoning', 'WISC5_FigureWeights')], cex = 0.5)
```

```{r message=FALSE, warning=FALSE, fig.align='center'}
ggplot(full_dat, aes(x= log(WISC4_Vocabulary), y=mABC_TotalStandardScore)) + 
  geom_jitter() +
  facet_grid(. ~ PrimaryDiagnosis) + 
  ggtitle('log(WISC4_Vocabulary) vs. mABC Total Standard Score')
```

```{r message=FALSE, warning=FALSE, fig.align='center'}
ggplot(full_dat, aes(x= log(WISC4_Information), y=mABC_TotalStandardScore)) + 
  geom_jitter() +
  facet_grid(. ~ PrimaryDiagnosis) + 
  ggtitle('log(WISC4_Information) vs. mABC Total Standard Score')
```

```{r}
ggplot(full_dat, aes(x= WISC4_Vocabulary + WISC4_Information + WISC4_Similarities + WISC4_BlockDesign + WISC4_PictureConcepts + WISC4_MatrixReasoning, y=mABC_TotalStandardScore)) + 
  geom_jitter() +
  facet_grid(. ~ PrimaryDiagnosis) + 
  ggtitle('WISC4_Design vs. mABC Total Standard Score')
```

